workflows:
  android-build:
    name: Build Android (Gradle)
    max_build_duration: 60
    environment:
      flutter: false
      vars:
        # Provide a base64-encoded keystore via Codemagic UI or encrypted vars
        KEYSTORE_BASE64: ""
        KEYSTORE_PASSWORD: ""
        KEY_ALIAS: ""
        KEY_PASSWORD: ""
      android:
        gradle_cache: true
    scripts:
      - name: Prepare
        script: |
          chmod +x ./gradlew || true
          if [ -n "${KEYSTORE_BASE64}" ]; then
            echo "${KEYSTORE_BASE64}" | base64 --decode > ./keystore.jks
          fi
      - name: Build Release
        script: ./gradlew :app:assembleRelease --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
