workflows:
  android-build:
    name: Build Android (Gradle)
    max_build_duration: 60
    environment:
      vars:
        KEYSTORE_BASE64:
          value: "<BASE64_KEYSTORE_PLACEHOLDER>"
          secure: true
        KEYSTORE_PASSWORD:
          value: "<KEYSTORE_PASSWORD>"
          secure: true
        KEY_ALIAS:
          value: "<KEY_ALIAS>"
          secure: true
        KEY_PASSWORD:
          value: "<KEY_PASSWORD>"
          secure: true
    scripts:
      - name: Prepare
        script: |
          chmod +x ./gradlew || true
          if [ -n "${KEYSTORE_BASE64}" ] && [ "${KEYSTORE_BASE64}" != "<BASE64_KEYSTORE_PLACEHOLDER>" ]; then
            echo "${KEYSTORE_BASE64}" | base64 --decode > ./keystore.jks
          fi
      - name: Build Release
        script: ./gradlew :app:assembleRelease --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
