workflows:
  android-build:
    name: Build Android (Gradle)
    max_build_duration: 60
    environment:
      vars:
        KEYSTORE_BASE64: REPLACE_WITH_BASE64_KEYSTORE
        KEYSTORE_PASSWORD: REPLACE_WITH_KEYSTORE_PASSWORD
        KEY_ALIAS: REPLACE_WITH_KEY_ALIAS
        KEY_PASSWORD: REPLACE_WITH_KEY_PASSWORD
    scripts:
      - name: Prepare
        script: |
          chmod +x ./gradlew || true
          if [ -n "${KEYSTORE_BASE64}" ] && [ "${KEYSTORE_BASE64}" != "<BASE64_KEYSTORE_PLACEHOLDER>" ]; then
            echo "${KEYSTORE_BASE64}" | base64 --decode > ./keystore.jks
          fi
      - name: Build Release
        script: ./gradlew :app:assembleRelease --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
